### ISSUE TITLE
Using custom string when doing auto export from Zotero/Better BibTeX

### ISSUE THREAD

**Issue by kshitijgoel007** [wkjarosz/rendering-bib#2]
Prof. Jarosz,

I started a similar project for my research domain.

I am trying to figure out how your automatically generated bib file contains the custom strings you define for journals and venues.

Do you manually edit the metadata in Zotero for this purpose and then let Better BibTeX export it?

Best,
Kshitij Goel

**Comment by wkjarosz** [comment]
Yes, for the journals I use often, I manually edit the metadata in Zotero to use the @string defines.
